import type { ReactNode, RefObject } from 'react'
import type { Cell, Diagnostic, PreviewPaper } from '../types'
import { AuthoringCodeEditor } from './AuthoringCodeEditor'
import { AuthoringStylePanel } from './AuthoringStylePanel'
import { ExplainPanel, ownerText } from './AuthoringPanels'
import type { AuthoringState } from './model'
import type { ExampleInputResult, PreviewResult, SemanticOperation, SourceOwner } from './service'

interface AuthoringInspectorProps {
  formulaEditor?: ReactNode
  inspector: string
  setInspector: (tab: string) => void
  state: AuthoringState
  selectedOwner?: SourceOwner
  textOwner?: SourceOwner
  classOwner?: SourceOwner
  owners: SourceOwner[]
  inputs: Record<string, string>
  input: (handle: string, text: string) => void
  apply: (owner: SourceOwner, value: SemanticOperation['value'], direction?: number, horizontal?: number) => void
  composing: boolean
  setComposing: (value: boolean) => void
  editing?: string
  propertyField: RefObject<HTMLInputElement | null>
  onCancel: () => void
  selectOwner: (owner: SourceOwner) => void
  onApplyClasses: (classes: string[]) => void
  multipleClasses: boolean
  selectedCell?: Cell
  preview?: PreviewResult
  caseId: string
  exampleInputLabel: string
  exampleEnabled: boolean
  exampleText: string
  example?: ExampleInputResult
  candidate?: PreviewPaper
  onExampleChange: (text: string) => void
  onPreviewExample: () => void
}

function responseMessages(result: ExampleInputResult) {
  const body = result.response as
    { diagnostics?: Diagnostic[]; error?: { message?: string }; message?: string } | undefined
  return body?.diagnostics?.map((diagnostic) => diagnostic.message).join(' · ') ?? body?.error?.message ?? body?.message
}

function propertyValue(owner: SourceOwner, text: string): SemanticOperation['value'] {
  if (owner.property === 'hide-zero') return text === 'true' ? true : text === 'false' ? false : text
  if (owner.property === 'precision' && /^\d+$/.test(text) && Number.isSafeInteger(Number(text))) return Number(text)
  return text
}

export function AuthoringInspector(props: AuthoringInspectorProps) {
  const {
    formulaEditor,
    inspector,
    setInspector,
    state,
    selectedOwner,
    textOwner,
    classOwner,
    owners,
    inputs,
    input,
    apply,
    composing,
    setComposing,
    editing,
    propertyField,
    onCancel,
    selectOwner,
    onApplyClasses,
    multipleClasses,
    selectedCell,
    preview,
    caseId,
    exampleInputLabel,
    exampleEnabled,
    exampleText,
    example,
    candidate,
    onExampleChange,
    onPreviewExample,
  } = props
  const channel =
    inspector === 'Example input'
      ? 'Example input'
      : selectedOwner && !selectedOwner.editable
        ? `Read-only · ${selectedOwner.reason ?? 'Generated by the engine'}`
        : 'ƒ Template definition · simulated owner'
  return (
    <aside className="author-card" data-author-region="inspector" aria-label="Inspector">
      <div className="author-tabs" role="tablist" aria-label="Inspector tabs">
        {['Property', 'Style', 'Explain', 'Example input'].map((tab) => (
          <button key={tab} role="tab" aria-selected={inspector === tab} onClick={() => setInspector(tab)}>
            {tab}
          </button>
        ))}
      </div>
      <span className="author-definition" data-testid="authoring-channel">
        {channel}
      </span>
      <p className="author-reference">
        {selectedOwner
          ? `${selectedOwner.document} › ${selectedOwner.declaration} › ${selectedOwner.property}`
          : 'Select a cell to see its owner'}
      </p>
      {inspector === 'Property' && formulaEditor}
      {inspector === 'Property' && !formulaEditor && (
        <>
          {textOwner ? (
            <>
              <label className="author-field">
                Property text
                {textOwner.property === 'note' ? (
                  <AuthoringCodeEditor
                    ariaLabel="Property text"
                    value={inputs[textOwner.handle] ?? ownerText(textOwner)}
                    onChange={(value) => input(textOwner.handle, value)}
                    onCommit={(value) => apply(textOwner, value)}
                    onCancel={() => {
                      input(textOwner.handle, ownerText(textOwner))
                      onCancel()
                    }}
                    onCompositionChange={setComposing}
                    readOnly={!textOwner.editable || !!state.saving}
                    autoFocus={editing === textOwner.handle}
                    selectAll
                    editorKey={textOwner.handle}
                  />
                ) : (
                  <input
                    ref={propertyField}
                    aria-label="Property text"
                    disabled={!textOwner.editable || !!state.saving}
                    value={inputs[textOwner.handle] ?? ownerText(textOwner)}
                    onChange={(event) => input(textOwner.handle, event.target.value)}
                    onCompositionStart={() => setComposing(true)}
                    onCompositionEnd={() => setComposing(false)}
                    onKeyDown={(event) => {
                      if (composing || event.nativeEvent.isComposing || event.nativeEvent.keyCode === 229) return
                      if (event.key === 'Enter') {
                        event.preventDefault()
                        apply(
                          textOwner,
                          propertyValue(textOwner, inputs[textOwner.handle] ?? ownerText(textOwner)),
                          event.ctrlKey || event.metaKey ? 0 : event.shiftKey ? -1 : 1,
                        )
                      }
                      if (event.key === 'Tab') {
                        event.preventDefault()
                        apply(
                          textOwner,
                          propertyValue(textOwner, inputs[textOwner.handle] ?? ownerText(textOwner)),
                          0,
                          event.shiftKey ? -1 : 1,
                        )
                      }
                      if (event.key === 'Escape') {
                        input(textOwner.handle, ownerText(textOwner))
                        onCancel()
                      }
                    }}
                  />
                )}
              </label>
              {state.preview.status === 'unavailable' && (
                <p role="status">Edit retained · no engine preview is recorded for this draft.</p>
              )}
              <button
                disabled={!textOwner.editable || !!state.saving || composing}
                onClick={() => {
                  const text = inputs[textOwner.handle] ?? ownerText(textOwner)
                  apply(textOwner, propertyValue(textOwner, text))
                }}
              >
                Apply property
              </button>
            </>
          ) : (
            <p>{selectedOwner?.reason ?? 'Generated by the engine'}</p>
          )}
          {selectedOwner && !selectedOwner.editable && <p>{selectedOwner.reason}</p>}
          <h3>Finite layout options</h3>
          {owners
            .filter((owner) => owner.kind === 'layout' && ['title', 'precision', 'hide-zero'].includes(owner.property))
            .map((owner) => (
              <button key={owner.handle} onClick={() => selectOwner(owner)}>
                {owner.property} · whole Paper
              </button>
            ))}
        </>
      )}
      {inspector === 'Style' && (
        <AuthoringStylePanel
          owner={classOwner}
          documents={state.documents}
          value={
            classOwner ? (inputs[classOwner.handle] ?? ownerText(classOwner)).trim().split(/\s+/).filter(Boolean) : []
          }
          onChange={(classes) => {
            if (classOwner) input(classOwner.handle, classes.join(' '))
          }}
          onApply={() =>
            onApplyClasses(
              classOwner
                ? (inputs[classOwner.handle] ?? ownerText(classOwner)).trim().split(/\s+/).filter(Boolean)
                : [],
            )
          }
          disabled={!!state.saving || composing}
          cell={selectedCell}
          multiple={multipleClasses}
        />
      )}
      {inspector === 'Explain' && (
        <ExplainPanel
          explain={selectedOwner?.nodeId ? preview?.responses.explains[selectedOwner.nodeId]?.data : undefined}
          value={selectedOwner?.nodeId ? preview?.responses.run?.data.values[selectedOwner.nodeId]?.[''] : undefined}
          previewSequence={preview?.draftSequence}
        />
      )}
      {inspector === 'Example input' && (
        <>
          <p>Changes example inputs in {caseId} — not the template.</p>
          <label className="author-field">
            {exampleInputLabel}
            <input
              aria-label="Example input"
              value={exampleText}
              disabled={!exampleEnabled}
              onChange={(event) => {
                onExampleChange(event.target.value)
              }}
              onCompositionStart={() => setComposing(true)}
              onCompositionEnd={() => setComposing(false)}
            />
          </label>
          <button disabled={!exampleEnabled || composing} onClick={onPreviewExample}>
            Preview example input
          </button>
          {!exampleEnabled && <p>Combined template and example-input preview needs contract G-A4.</p>}
          {example?.kind === 'invalid' && (
            <p role="alert">{responseMessages(example) ?? 'Recorded engine input validation failed.'}</p>
          )}
          {example?.kind === 'unrecorded' && <p>{example.reason}</p>}
          {candidate && (
            <>
              <p>Candidate example input preview · recorded, not saved</p>
              <pre>{JSON.stringify(candidate.difference, null, 2)}</pre>
            </>
          )}
          <p>Example input changes have a separate channel; this prototype does not write the case.</p>
        </>
      )}
    </aside>
  )
}
